version: '3'
services:
  webserver-alpine:
    image: nginx:${NGINX_VERSION}
    container_name: webserver-alpine
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    volumes:
      - ${APPLICATION_DIR}:${WORKING_DIR}/${APPLICATION_NAME}
      - ./nginx/site.conf:${NGINX_DEFAULT_CONF}
    depends_on:
      - php-fpm-alpine
    links:
      - php-fpm-alpine
    networks:
      - docker-nginx-php-fpm-alpine
  php-fpm-alpine:
    build:
      dockerfile: ./php-fpm/Dockerfile
      context: .
    container_name: php-fpm-alpine
    working_dir: ${WORKING_DIR}
    volumes:
      - ${APPLICATION_DIR}:${WORKING_DIR}/${APPLICATION_NAME}
    networks:
      - docker-nginx-php-fpm-alpine
networks:
  docker-nginx-php-fpm-alpine:
    driver: bridge

